# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pic',
        ),
    ]
