# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='path',
            field=models.CharField(default='/', max_length=200, verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
