# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u4e66\u540d')),
                ('author', models.CharField(max_length=150, verbose_name='\u4f5c\u8005')),
                ('pubdate', models.CharField(max_length=20, verbose_name='\u51fa\u7248\u65e5\u671f')),
                ('type', models.CharField(max_length=20, verbose_name='\u7c7b\u578b')),
                ('ISBN', models.CharField(max_length=20, verbose_name='ISBN')),
                ('path', models.CharField(default='/', max_length=200, verbose_name='\u8def\u5f84')),
                ('isshow', models.IntegerField(choices=[(1, '\u5141\u8bb8\u5c55\u793a'), (2, '\u4e0d\u5141\u8bb8\u5c55\u793a')], default=2, verbose_name='\u5141\u8bb8\u663e\u793a')),
                ('isrecommend', models.IntegerField(choices=[(1, '\u662f'), (2, '\u4e0d\u63a8\u8350')], default=2, verbose_name='\u662f\u5426\u63a8\u8350')),
            ],
        ),
        migrations.CreateModel(
            name='gitbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('author', models.CharField(max_length=20, verbose_name='\u4f5c\u8005')),
                ('path', models.CharField(default='/', max_length=100, verbose_name='\u8def\u5f84')),
                ('isshow', models.IntegerField(choices=[(1, '\u5141\u8bb8\u5c55\u793a'), (2, '\u4e0d\u5141\u8bb8\u5c55\u793a')], default=2, verbose_name='\u5141\u8bb8\u663e\u793a')),
                ('isrecommend', models.IntegerField(choices=[(1, '\u662f'), (2, '\u4e0d\u63a8\u8350')], default=2, verbose_name='\u662f\u5426\u63a8\u8350')),
            ],
        ),
    ]
