# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gitbok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('path', models.CharField(default='/', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='path',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
