# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='isrecommend',
            field=models.IntegerField(choices=[(1, '\u63a8\u8350'), (2, '\u4e0d\u63a8\u8350')], default=2, verbose_name='\u662f\u5426\u63a8\u8350'),
        ),
        migrations.AlterField(
            model_name='gitbook',
            name='isrecommend',
            field=models.IntegerField(choices=[(1, '\u63a8\u8350'), (2, '\u4e0d\u63a8\u8350')], default=2, verbose_name='\u662f\u5426\u63a8\u8350'),
        ),
    ]
