# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_auto_20170507_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitbook',
            name='url',
        ),
        migrations.AddField(
            model_name='gitbook',
            name='name',
            field=models.CharField(default='noname', max_length=50, verbose_name='\u9879\u76ee\u540d'),
        ),
    ]
