# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_auto_20170319_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='gitbo0k',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('path', models.CharField(default='/', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='gitbok',
        ),
    ]
