# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_auto_20170510_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitbook',
            name='realpath',
            field=models.CharField(default='unknow', max_length=50, verbose_name='\u9879\u76ee\u539f\u59cb\u5730\u5740'),
        ),
    ]
