# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_auto_20170331_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gitbo0k',
            new_name='gitbook',
        ),
    ]
