# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0004_auto_20170331_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
