# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0005_auto_20170403_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
