# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0006_auto_20170403_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='path',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
