# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='bookID',
            field=models.IntegerField(verbose_name='\u4e66\u7c4dID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='userID',
            field=models.IntegerField(verbose_name='\u7528\u6237ID'),
        ),
    ]
